services:
  umbraco:
    image: tugboatqa/debian:12
    default: true
    commands:
      init:
        - wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb &&
            dpkg -i packages-microsoft-prod.deb &&
            rm packages-microsoft-prod.deb
        - apt-get update && apt-get install -y dotnet-sdk-8.0
        - mkdir -p /app
        - mkdir -p /etc/service/umbraco
        - echo '#!/bin/sh' > /etc/service/umbraco/run
        - echo '/usr/bin/dotnet run --no-build --urls=http://0.0.0.0:80 --project $TUGBOAT_ROOT' >> /etc/service/umbraco/run
        - chmod +x /etc/service/umbraco/run
      update:
        - tar -xvzf .tugboat/data.tgz
      build:
        - dotnet build umbraco.csproj
      # Sleep for 10 seconds to give the server time to start.
      ready: test ! -d $TUGBOAT_ROOT/.tugboat || sleep 10